import "./globals.css";
import "@splidejs/splide/dist/css/themes/splide-default.min.css";

export const metadata = {
  title: "ABCANDY",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
